openapi: "3.0.0"
info:
  title: "Moja chitalna"
  version: "1.0.0"
  description: "Moja chitalna e aplikacija za rezervacija na mesto za uchenje vo chitalna"
servers:
  - url: http://localhost:8080/{basePath}
    description: The backend API of the project
    variables:
      basePath:
        default: /api
paths:
  /sample:
    get:
      summary: Get all samples
      operationId: getSamples
      tags:
        - sample
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Samples'
    post:
      summary: Add a new sample
      operationId: addSample
      tags:
        - sample
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleItem'
      responses:
        200:
          description: OK

components:
  schemas:
    Samples:
      type: object
      properties:
        sample_items:
          type: array
          items:
            $ref: '#/components/schemas/SampleItem'

    SampleItem:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: integer
          format: int64
          example: 1
        text:
          type: string
          example: "Sample item"